services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: eshop-db
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - mssql-data:/var/opt/mssql

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite-local
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: eshop-redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data

  eshop:
    build:
      context: ./backend
      dockerfile: eShop.Host/Dockerfile
    container_name: eshop-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - azurite
      - redis
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=master;User Id=sa;Password=Password123!;TrustServerCertificate=True
      - ConnectionStrings__Redis=redis:6379
      - AzureBlobStorage__ConnectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
      - JwtSettings__Secret=MyDockerDevSuperSecretKey1234567890
      - JwtSettings__Issuer=https://localhost:8080
      - JwtSettings__Audience=eShopAudience
      - JwtSettings__ExpirationInMinutes=60
      - EmailSettings__SmtpServer=smtp.gmail.com
      - EmailSettings__SmtpPort=587
      - EmailSettings__EnableSsl=true
      - EmailSettings__SmtpUsername=******
      - EmailSettings__SmtpPassword=******
      - EmailSettings__FromEmail=******
      - EmailSettings__FromName=eShop
      - TwilioSettings__AccountSid=******
      - TwilioSettings__AuthToken=******
      - TwilioSettings__FromPhoneNumber=******

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eshop-frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - eshop
    environment:
      - NEXT_PUBLIC_API_URL=http://eshop:8080/api

networks:
  app-network:
    driver: bridge

volumes:
  mssql-data:
  redis-data:
