services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: eshop-db
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - mssql-data:/var/opt/mssql

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite-local
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: eshop-redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data

  eshop:
    build:
      context: .
      dockerfile: eShop/Dockerfile
    container_name: eshop-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - azurite
      - redis
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=eShopDB;User Id=sa;Password=Password123!;TrustServerCertificate=True
      - ConnectionStrings__Redis=redis:6379
      - AzureBlobStorage__ConnectionString=UseDevelopmentStorage=true
      - JwtSettings__Secret=MyDockerDevSuperSecretKey1234567890
      - JwtSettings__Issuer=https://localhost:8080
      - JwtSettings__Audience=eShopAudience
      - JwtSettings__ExpirationInMinutes=60

networks:
  app-network:
    driver: bridge

volumes:
  mssql-data:
  redis-data: