version: '3.8'

services:
  eshop:
    image: eshop
    build:
      context: .
      dockerfile: eShop/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION=DockerConnection

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - mssql-data:/var/opt/mssql  

networks:
  app-network:
    driver: bridge

volumes:
  mssql-data:
